name: Deploy Site

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug environment
        run: |
          echo "Custom domain detected (CNAME file present)"
          echo "Building for root path deployment"
          
      - name: Build site
        run: npm run build
        # Note: Not setting GITHUB_PAGES=true because we're using a custom domain
        # The presence of CNAME file means GitHub Pages serves from root path

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 